# Generated by Django 6.0.3 on 2026-03-26 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cnc_v2', '0003_wasteprocessing_batch_number_wasteprocessing_notes_and_more'),
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('current_stage', models.CharField(choices=[('ARMIRLASH', 'Armirlash (Reinforcing)'), ('SHPAKLYOVKA', 'Shpaklyovka (Plastering)'), ('DRYING', 'Quritish (Drying)'), ('READY', 'Tayyor (Ready for Sklad 4)')], default='ARMIRLASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('RUNNING', 'Jarayonda'), ('PAUSED', 'To‘xtatilgan'), ('COMPLETED', 'Tugallangan'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cnc_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_jobs', to='cnc_v2.cncjob')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material')),
            ],
        ),
        migrations.CreateModel(
            name='FinishingStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ARMIRLASH', 'Armirlash (Reinforcing)'), ('SHPAKLYOVKA', 'Shpaklyovka (Plastering)'), ('DRYING', 'Quritish (Drying)'), ('READY', 'Tayyor (Ready for Sklad 4)')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='finishing_v2.finishingjob')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
