# Generated by Django 6.0.3 on 2026-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingjob',
            name='finished_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishingjob',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finishingjob',
            name='total_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishingjob',
            name='waste_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finishingjob',
            name='quantity',
            field=models.IntegerField(help_text='Planned quantity'),
        ),
    ]
