# Generated by Django 6.0.3 on 2026-03-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing_v2', '0002_finishingjob_finished_quantity_and_more'),
        ('production_v2', '0007_alter_productionorder_status_qualitycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingjob',
            name='order_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_jobs', to='production_v2.productionorderstage'),
        ),
    ]
