# Generated by Django 6.0.3 on 2026-04-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_v2', '0009_saleitem_batch_number_saleitem_source_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLIENT', 'Mijoz uchun (Client)'), ('PROJECT', 'Ichki loyiha uchun (Project)')], default='CLIENT', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda (Pending)'), ('SENT', 'Yuborildi (Sent)'), ('ARRIVED', 'Yetib bordi (Arrived)'), ('RECEIVED', 'Qabul qilindi (Received)'), ('CANCELLED', 'Bekor qilingan (Cancelled)')], default='PENDING', max_length=20)),
                ('destination_manual', models.CharField(blank=True, help_text='Manual address if needed', max_length=255)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('destination_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_deliveries', to='sales_v2.customer')),
            ],
        ),
    ]
