# Generated by Django 6.0.3 on 2026-04-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_inventorybatch_inventorymovement_delete_inventory'),
        ('logistics', '0001_initial'),
        ('projects', '0001_initial'),
        ('sales_v2', '0009_saleitem_batch_number_saleitem_source_warehouse'),
        ('warehouse_v2', '0009_batchreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='destination_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_deliveries', to='projects.constructionproject'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_shipments', to='sales_v2.invoice'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material'),
        ),
    ]
