# Generated by Django 6.0.3 on 2026-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Admin', 'Admin'), ('WarehouseOperator', 'Warehouse Operator'), ('ProductionOperator', 'Production Operator'), ('CNCOperator', 'CNC Operator'), ('FinishingOperator', 'Finishing Operator'), ('WasteOperator', 'Waste Operator'), ('Salesperson', 'Salesperson')], max_length=20),
        ),
    ]
