# Generated by Django 6.0.3 on 2026-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_warehouses',
            field=models.ManyToManyField(blank=True, to='warehouse.warehouse'),
        ),
    ]
