# Generated by Django 6.0.3 on 2026-04-17 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('NEGATIVE_STOCK', 'Minus sklad taqiqlash'), ('NO_DOCUMENT', 'Hujjatsiz operatsiya'), ('TAX_LIMIT', 'Soliq chegarasi buzilishi')], max_length=50, unique=True)),
                ('severity', models.CharField(choices=[('WARNING', 'Ogohlantirish'), ('BLOCK', 'Bloklash')], default='BLOCK', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('context_data', models.JSONField(blank=True, help_text='Buzilgan obyekt xususiyatlari', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancerule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(help_text='Hujjat raqami', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Faktura'), ('CONTRACT', 'Shartnoma'), ('ACT', 'Dalolatnoma'), ('TAX_REPORT', 'Soliq Hisoboti'), ('CERTIFICATE', 'Sertifikat'), ('OTHER', 'Boshqa')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Imzoga kutilmoqda'), ('SIGNED', 'Imzolangan'), ('ARCHIVED', 'Arxivlangan')], default='DRAFT', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='compliance_docs/')),
                ('digital_signature', models.TextField(blank=True, help_text='E-imzo xeshi', null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yuridik Hujjat',
                'verbose_name_plural': 'Yuridik Hujjatlar',
            },
        ),
    ]
