# Generated by Django 6.0.3 on 2026-03-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0002_stock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='currency',
            field=models.CharField(default='UZS', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Qabul qilindi'), ('INSPECTION', 'Tekshiruvda'), ('IN_STOCK', 'Omborda'), ('RESERVED', 'Band qilingan'), ('DEPLETED', 'Tugatilgan')], default='IN_STOCK', max_length=20),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='warehouse_v2.supplier'),
        ),
    ]
