# Generated by Django 6.0.3 on 2026-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('RAW', 'Xom-ashyo'), ('SEMI', 'Yarim tayyor mahsulot'), ('FINISHED', 'Tayyor mahsulot'), ('OTHER', 'Boshqa')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
