# Generated by Django 6.0.3 on 2026-03-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0004_material_category_material_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransfer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('COMPLETED', 'Yakunlandi'), ('CANCELLED', 'Bekor qilindi')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Qabul qilindi'), ('INSPECTION', 'Tekshiruvda'), ('IN_STOCK', 'Omborda'), ('RESERVED', 'Band qilingan'), ('DEPLETED', 'Tugatilgan'), ('CANCELLED', 'Bekor qilindi')], default='IN_STOCK', max_length=20),
        ),
    ]
