# Generated by Django 6.0.3 on 2026-03-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0005_warehousetransfer_notes_warehousetransfer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='remaining_quantity',
            field=models.FloatField(default=0),
        ),
    ]
