# Generated by Django 6.0.3 on 2026-03-28 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0006_rawmaterialbatch_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
