# Generated by Django 6.0.3 on 2026-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0007_rawmaterialbatch_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='reserved_quantity',
            field=models.FloatField(default=0),
        ),
    ]
