# Generated by Django 6.0.3 on 2026-03-28 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentdelivery_printrecord'),
        ('warehouse_v2', '0008_rawmaterialbatch_reserved_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse_v2.rawmaterialbatch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='documents.document')),
            ],
        ),
    ]
