# Generated by Django 6.0.3 on 2026-04-17 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0009_batchreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('IN_PROGRESS', 'Sanalyapti'), ('REVIEW', 'Tasdiqlash kutilmoqda'), ('COMPLETED', 'Yakunlangan')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_approved', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_conducted', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.warehouse')),
            ],
            options={
                'verbose_name': 'Sklad Auditi',
                'verbose_name_plural': 'Sklad Auditlari',
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.FloatField(help_text='Tizimdagi qoldiq')),
                ('actual_qty', models.FloatField(blank=True, help_text='Haqiqiy sanalgan qoldiq', null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse_v2.inventoryaudit')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material')),
            ],
        ),
    ]
