# Generated by Django 6.0.3 on 2026-04-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0010_inventoryaudit_inventoryauditline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='min_level',
            field=models.FloatField(default=0, help_text='Ogohlantirish darajasi'),
        ),
    ]
