# Generated by Django 6.0.3 on 2026-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0011_stock_min_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchreservation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryauditline',
            name='actual_qty',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Haqiqiy sanalgan qoldiq', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryauditline',
            name='system_qty',
            field=models.DecimalField(decimal_places=3, help_text='Tizimdagi qoldiq', max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='currency',
            field=models.CharField(default='UZS', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Ogohlantirish darajasi', max_digits=18),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
    ]
