# Generated by Django 6.0.3 on 2026-04-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0006_inventorybatch_inventorymovement_delete_inventory'),
        ('warehouse_v2', '0009_batchreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Rejalashtirilgan'), ('IN_PROGRESS', 'Jarayonda'), ('PAUSED', "To'xtatilgan"), ('COMPLETED', 'Tugallangan'), ('CANCELLED', 'Bekor qilingan')], default='PLANNED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorybatch')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_v2.warehouse')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorymovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='projects.constructionproject')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction')),
            ],
        ),
    ]
