# Generated by Django 6.0.3 on 2026-03-21 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNCOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('program_file', models.FileField(blank=True, null=True, upload_to='cnc_programs/')),
                ('output_volume', models.FloatField(help_text='Volume of finished products in m3')),
                ('waste_volume', models.FloatField(help_text='Volume of waste in m3')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_amount', models.FloatField(help_text='Amount of raw waste in kg')),
                ('processed_amount', models.FloatField(help_text='Amount of recycled/processed material in kg')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_processing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
