# Generated by Django 6.0.3 on 2026-03-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_v2', '0001_initial'),
        ('production_v2', '0004_blockproduction_density_blockproduction_height_and_more'),
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteprocessing',
            name='processed_amount',
        ),
        migrations.RemoveField(
            model_name='wasteprocessing',
            name='waste_amount',
        ),
        migrations.AddField(
            model_name='wasteprocessing',
            name='status',
            field=models.CharField(choices=[('RAW', 'Xom-ashyo (Chiqindi)'), ('RECYCLED', 'Qayta ishlangan')], default='RAW', max_length=20),
        ),
        migrations.AddField(
            model_name='wasteprocessing',
            name='waste_amount_kg',
            field=models.FloatField(default=0, help_text='Amount in kg'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CNCJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('quantity_planned', models.IntegerField()),
                ('quantity_finished', models.IntegerField(default=0)),
                ('waste_m3', models.FloatField(default=0, help_text='Volume of waste in m3')),
                ('machine_id', models.CharField(choices=[('CNC-1', 'CNC #1'), ('CNC-2', 'CNC #2')], max_length=50)),
                ('status', models.CharField(choices=[('CREATED', 'Yaratildi'), ('RUNNING', 'Jarayonda'), ('PAUSED', 'To‘xtatilgan'), ('COMPLETED', 'Tugallangan'), ('CANCELLED', 'Bekor qilindi')], default='CREATED', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnc_jobs', to='production_v2.blockproduction')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnc_job', to='production_v2.productionorderstage')),
                ('output_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material')),
            ],
        ),
        migrations.AddField(
            model_name='wasteprocessing',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastes', to='cnc_v2.cncjob'),
        ),
        migrations.DeleteModel(
            name='CNCOrder',
        ),
    ]
