# Generated by Django 6.0.3 on 2026-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_v2', '0002_remove_wasteprocessing_processed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteprocessing',
            name='batch_number',
            field=models.CharField(blank=True, help_text="Partiya raqami (agar CNC job bo'lmasa)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasteprocessing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteprocessing',
            name='reason',
            field=models.CharField(choices=[('CUTTING', 'Kesish chiqindisi'), ('DEFECT', 'Brak (Sifat nazoratidan o‘tmadi)'), ('TRANSPORT', 'Transportdagi zarar'), ('STORAGE', 'Saqlashdagi yo‘qotish'), ('OTHER', 'Boshqa sabab')], default='CUTTING', max_length=30),
        ),
        migrations.AddField(
            model_name='wasteprocessing',
            name='source_department',
            field=models.CharField(choices=[('CNC', 'CNC Sexi'), ('BLOCK', 'Blok Kesish'), ('COATING', 'Armirlash (Coating)'), ('PACKAGING', 'Qadoqlash'), ('OTHER', 'Boshqa')], default='OTHER', max_length=30),
        ),
    ]
