# Generated by Django 6.0.3 on 2026-03-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_v2', '0003_wasteprocessing_batch_number_wasteprocessing_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncjob',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cncjob',
            name='total_duration_seconds',
            field=models.IntegerField(default=0, help_text='Cumulative work time in seconds'),
        ),
    ]
