# Generated by Django 6.0.3 on 2026-04-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_v2', '0004_cncjob_last_started_at_cncjob_total_duration_seconds'),
        ('production_v2', '0010_productionbatch_overheadcost_laborcost_energyusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncjob',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnc_jobs', to='production_v2.productionbatch'),
        ),
    ]
