# Generated by Django 6.0.3 on 2026-03-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('norm_percent', models.FloatField(default=5.0, help_text='Ruxsat etilgan chiqindi foizi (batchga nisbatan)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chiqindi turi',
                'verbose_name_plural': 'Chiqindi turlari',
            },
        ),
        migrations.CreateModel(
            name='WasteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('source_department', models.CharField(choices=[('CNC', 'CNC Sexi'), ('FINISHING', 'Pardozlash Sexi'), ('PRODUCTION', 'Ishlab chiqarish (Quyish)'), ('WAREHOUSE', 'Ombor'), ('OTHER', 'Boshqa')], default='OTHER', max_length=30)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_kg', models.FloatField(help_text='Chiqindi vazni (kg)')),
                ('status', models.CharField(choices=[('PENDING', 'Qabul qilindi'), ('PROCESSING', 'Qayta ishlanmoqda'), ('COMPLETED', 'Yakunlandi')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('recycled_weight_kg', models.FloatField(default=0, help_text='Qayta ishlangan vazn (kg)')),
                ('loss_weight_kg', models.FloatField(default=0, help_text="Yo'qotilgan/utilizatsiya qilingan vazn (kg)")),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='waste_v2.wastecategory')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiqindi vazifasi',
                'verbose_name_plural': 'Chiqindi vazifalari',
            },
        ),
    ]
