# Generated by Django 6.0.3 on 2026-03-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_warehouses',
            field=models.CharField(default='*', help_text='Comma separated IDs or * for all', max_length=255),
        ),
    ]
