# Generated by Django 6.0.3 on 2026-03-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_warehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('WAREHOUSE_OPERATOR', 'Warehouse Operator'), ('PRODUCTION_OPERATOR', 'Production Operator'), ('CNC_OPERATOR', 'CNC Operator'), ('FINISHING_OPERATOR', 'Finishing Operator'), ('WASTE_OPERATOR', 'Waste Operator'), ('SALES_MANAGER', 'Sales Manager')], max_length=50),
        ),
    ]
