# Generated by Django 6.0.3 on 2026-03-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'ERP Permission',
                'verbose_name_plural': 'ERP Permissions',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='accounts.erppermission'),
        ),
        migrations.CreateModel(
            name='ERPRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.erppermission')),
            ],
            options={
                'verbose_name': 'ERP Role',
                'verbose_name_plural': 'ERP Roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.erprole'),
        ),
    ]
