# Generated by Django 6.0.3 on 2026-03-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_department_user_last_login_ip_user_notes_and_more'),
        ('warehouse_v2', '0004_material_category_material_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_warehouses',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_warehouses',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='warehouse_v2.warehouse'),
        ),
    ]
