# Generated by Django 6.0.3 on 2026-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reserved_quantity',
            field=models.FloatField(default=0),
        ),
    ]
