# Generated by Django 6.0.3 on 2026-04-05 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_reserved_quantity'),
        ('warehouse_v2', '0009_batchreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(choices=[('INTERNAL', "O'z mahsulotimiz (Produksiya)"), ('EXTERNAL', 'Tashqaridan kelgan mahsulot')], default='EXTERNAL', max_length=20)),
                ('initial_weight', models.DecimalField(decimal_places=3, help_text='Starting weight in grams/kg', max_digits=15)),
                ('current_weight', models.DecimalField(decimal_places=3, help_text='Current available weight', max_digits=15)),
                ('reserved_weight', models.DecimalField(decimal_places=3, default=0, help_text='Reserved weight for orders', max_digits=15)),
                ('status', models.CharField(choices=[('IN_STOCK', 'Omborda'), ('RESERVED', 'Band qilingan'), ('DEPLETED', 'Tugatilgan'), ('PROJECT_USE', 'Loyiha uchun sarflangan'), ('WASTE', 'Chiqindi')], default='IN_STOCK', max_length=20)),
                ('qr_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_v2.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='warehouse_v2.material')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('type', models.CharField(choices=[('IN', 'Kirim (In)'), ('OUT', 'Chiqim (Out)'), ('TRANSFER', "Ko'chirish (Transfer)"), ('ADJUSTMENT', 'Tuzatish (Adjustment)')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='e.g., Zames-101, Sale-501, Project-X', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventorybatch')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='warehouse_v2.warehouse')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='warehouse_v2.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
