# Generated by Django 6.0.3 on 2026-03-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('TRANSFER', 'Transfer'), ('PRODUCTION', 'Production')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_wh', to='warehouse.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('to_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_wh', to='warehouse.warehouse')),
            ],
        ),
    ]
