# Generated by Django 6.0.3 on 2026-03-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('TRANSFER', 'Transfer'), ('PRODUCTION', 'Production'), ('SALE', 'Sale')], max_length=20),
        ),
    ]
