# Generated by Django 6.0.3 on 2026-03-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_type'),
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_wh', to='warehouse_v2.warehouse'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_wh', to='warehouse_v2.warehouse'),
        ),
    ]
