# Generated by Django 6.0.3 on 2026-03-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('HISOB_FAKTURA_KIRIM', 'Hisob-faktura (Kirim)'), ('HISOB_FAKTURA_CHIQIM', 'Hisob-faktura (Chiqim)'), ('ICHKI_NAKLADNOY', 'Ichki Nakladnoy'), ('TRANSFER_ORDER', 'Transfer Order'), ('PRODUCTION_ORDER', 'Production Order'), ('ISSUE_ORDER', 'Issue Order'), ('ZAMES_LOG', 'Zames Log (Expansion)'), ('BUNKER_ENTRY', 'Bunker Entry'), ('FORMOVKA_LOG', 'Formovka Log'), ('STAGE_UPDATE', 'Stage Update (CNC/Finishing)')], max_length=20),
        ),
    ]
