# Generated by Django 6.0.3 on 2026-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_client_document_from_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='currency',
            field=models.CharField(default='UZS', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='document',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
