# Generated by Django 6.0.3 on 2026-03-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_currency_document_exchange_rate_and_more'),
        ('sales_v2', '0002_invoice_status'),
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales_v2.customer'),
        ),
        migrations.AlterField(
            model_name='document',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_docs', to='warehouse_v2.warehouse'),
        ),
        migrations.AlterField(
            model_name='document',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_docs', to='warehouse_v2.warehouse'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material'),
        ),
    ]
