# Generated by Django 6.0.3 on 2026-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_client_alter_document_from_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
