# Generated by Django 6.0.3 on 2026-03-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentitem_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Yaratildi'), ('APPROVED', 'Tasdiqlandi'), ('IN_TRANSIT', "Yo'lda"), ('DONE', 'Qabul qilindi'), ('CANCELLED', 'Bekor qilindi'), ('RETURNED', 'Qaytarildi')], default='CREATED', max_length=20),
        ),
    ]
