# Generated by Django 6.0.3 on 2026-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CREATED', 'Yaratildi'), ('CONFIRMED', 'Tasdiqlangan'), ('APPROVED', 'Tasdiqlandi'), ('IN_PROGRESS', 'Jarayonda'), ('IN_TRANSIT', "Yo'lda"), ('DONE', 'Yakunlandi'), ('CANCELLED', 'Bekor qilingan'), ('RETURNED', 'Qaytarildi')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('HISOB_FAKTURA_KIRIM', 'Hisob-faktura (Kirim)'), ('HISOB_FAKTURA_CHIQIM', 'Hisob-faktura (Chiqim)'), ('ICHKI_YUK_XATI', 'Ichki yuk xati'), ('OTKAZMA_BUYRUGI', 'O‘tkazma buyrug‘i'), ('PRODUCTION_ORDER', 'Ishlab chiqarish buyrug‘i'), ('ISSUE_ORDER', 'Berish buyrug‘i'), ('ZAMES_LOG', 'Zames Jurnali (Kengaytirish)'), ('BUNKER_ENTRY', 'Bunker Kirimi'), ('FORMOVKA_LOG', 'Formovka Jurnali'), ('STAGE_UPDATE', 'Bosqich Yangilanishi (CNC/Pardozlash)')], max_length=20),
        ),
    ]
