# Generated by Django 6.0.3 on 2026-03-28 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_status_alter_document_type'),
        ('warehouse_v2', '0006_rawmaterialbatch_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='warehouse_v2.supplier'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='price_at_moment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
