# Generated by Django 6.0.3 on 2026-03-28 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_supplier_documentitem_price_at_moment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_signature_qr', models.TextField(blank=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_deliveries', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='PrintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='documents.document')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
