# Generated by Django 6.0.3 on 2026-03-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_v2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='branch',
            field=models.CharField(default='Asosiy Filial', max_length=100),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cashboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='finance/attachments/'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='department',
            field=models.CharField(choices=[('ADMIN', 'Administratsiya'), ('PRODUCTION', 'Ishlab chiqarish'), ('LOGISTICS', 'Logistika'), ('SALES', 'Sotuv'), ('OTHER', 'Boshqa')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='finance_v2.cashbox')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='finance_v2.cashbox')),
            ],
        ),
    ]
