# Generated by Django 6.0.3 on 2026-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_v2', '0002_cashbox_branch_cashbox_responsible_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbalance',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='overdue_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
