# Generated by Django 6.0.3 on 2026-03-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Muvaffaqiyatli'), ('ERROR', 'Xatolik'), ('WARNING', 'Ogohlantirish')], default='SUCCESS', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Yaratish'), ('UPDATE', 'Tahrirlash'), ('DELETE', "O'chirish"), ('LOGIN', 'Kirish'), ('LOGOUT', 'Chiqish'), ('TRANSFER', "O'tkazma"), ('ERROR', 'Xatolik')], max_length=20),
        ),
    ]
