# Generated by Django 6.0.3 on 2026-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_v2', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, help_text='Model nomi (masalan: Invoice)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, help_text="O'zgarishdan keyingi qiymat", null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, help_text="O'zgarishdan oldingi qiymat", null=True),
        ),
    ]
