# Generated by Django 6.0.3 on 2026-04-17 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('LOW_STOCK', 'Sklad kamayishi'), ('NEGATIVE_BALANCE', 'Minus balans'), ('BUDGET_EXCEEDED', 'Byudjet oshib ketishi'), ('COMPLIANCE_VIOLATION', 'Qoida buzilishi'), ('LARGE_TRANSACTION', 'Katta summa tranzaksiyasi')], max_length=50)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Chegara qiymati (limit)', max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', "Ma'lumot"), ('WARNING', 'Ogohlantirish'), ('CRITICAL', 'Kritik')], default='INFO', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
