# Generated by Django 6.0.3 on 2026-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAnomalyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('anomaly_type', models.CharField(choices=[('PROD_LOSS', 'Ishlab chiqarish brak darajasi'), ('PRICE_DUMP', 'Narxning keskin tushishi'), ('EXPENSE_SPIKE', 'Kutilmagan katta xarajat'), ('STRANGE_TIME', 'Tunda/Dam olish kunida operatsiya')], max_length=50)),
                ('normal_threshold', models.DecimalField(decimal_places=2, help_text='Odatdagi chegara (masalan % yoki summa)', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
