# Generated by Django 6.0.3 on 2026-03-21 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50)),
                ('block_count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DryingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('block_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_processes', to='production_v2.blockproduction')),
            ],
        ),
        migrations.CreateModel(
            name='Zames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zames_number', models.CharField(max_length=50, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('raw_material_weight', models.FloatField()),
                ('expanded_weight', models.FloatField()),
                ('dried_weight', models.FloatField()),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BunkerLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('required_time', models.IntegerField(help_text='Time required for rest in minutes')),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='production_v2.bunker')),
                ('zames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='production_v2.zames')),
            ],
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='zames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='production_v2.zames'),
        ),
    ]
