# Generated by Django 6.0.3 on 2026-03-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0001_initial'),
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='zames',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='zames',
            name='raw_material_weight',
        ),
        migrations.AddField(
            model_name='zames',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zames',
            name='input_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zames',
            name='machine_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zames',
            name='output_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zames',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zames',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('DONE', 'Tugallandi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='zames',
            name='dried_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='zames',
            name='expanded_weight',
            field=models.FloatField(default=0, help_text='Weight after primary expansion'),
        ),
        migrations.AddField(
            model_name='zames',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_v2.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Standard quantity for this recipe')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production_v2.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ZamesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_v2.rawmaterialbatch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_v2.material')),
                ('zames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production_v2.zames')),
            ],
        ),
    ]
