# Generated by Django 6.0.3 on 2026-03-26 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0002_recipe_rename_datetime_zames_created_at_and_more'),
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(help_text='Volume in blocks or cubic meters')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PLANNED', 'Rejalashtirilgan'), ('IN_PROGRESS', 'Jarayonda'), ('DELAYED', 'Kechikayotgan'), ('COMPLETED', 'Tugallangan'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=20)),
                ('progress', models.FloatField(default=0, help_text='Total completion percentage')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('source_order', models.CharField(blank=True, help_text="Link to MTO order or 'STOCK'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_v2.material')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('ZAMES', 'Zames (Mixing)'), ('DRYING', 'Quritish'), ('BUNKER', 'Bunker (Resting)'), ('FORMOVKA', 'Formovka (Molding)'), ('BLOK', 'Blok (Cutting/Sizing)'), ('CNC', 'CNC (Cutting)'), ('DEKOR', 'Dekor (Finishing)')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACTIVE', 'Aktiv'), ('COMPLETED', 'Tugallangan'), ('PAUSED', 'To‘xtatilgan')], default='PENDING', max_length=20)),
                ('sequence', models.IntegerField(default=0, help_text='Order of this stage in the pipeline')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_id', models.IntegerField(blank=True, help_text='ID of the related entity like Zames object', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='production_v2.productionorder')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
