# Generated by Django 6.0.3 on 2026-03-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0003_productionorder_productionorderstage'),
        ('warehouse_v2', '0003_rawmaterialbatch_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproduction',
            name='density',
            field=models.FloatField(default=20, help_text='kg/m3'),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='height',
            field=models.FloatField(default=500, help_text='mm'),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='length',
            field=models.FloatField(default=1000, help_text='mm'),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='status',
            field=models.CharField(choices=[('DRYING', 'Quritilmoqda'), ('READY', 'Tayyor'), ('DEFECT', 'Brak'), ('RESERVED', 'Band qilingan'), ('SOLD', 'Sotilgan')], default='DRYING', max_length=20),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='volume',
            field=models.FloatField(default=0, help_text='Total volume in m3'),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_v2.warehouse'),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='weight_per_block',
            field=models.FloatField(default=0, help_text='kg'),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='width',
            field=models.FloatField(default=500, help_text='mm'),
        ),
    ]
