# Generated by Django 6.0.3 on 2026-03-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0004_blockproduction_density_blockproduction_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Shoshilinch'), ('HIGH', 'Yuqori'), ('MEDIUM', 'O‘rtacha'), ('LOW', 'Past')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorderstage',
            name='actual_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionorderstage',
            name='waste_amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('DAY', 'Kunlik'), ('NIGHT', 'Tungi')], default='DAY', max_length=20)),
                ('target_volume', models.FloatField(default=0)),
                ('actual_volume', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(related_name='plans', to='production_v2.productionorder')),
            ],
        ),
    ]
