# Generated by Django 6.0.3 on 2026-03-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0005_productionorder_notes_productionorder_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderstage',
            name='current_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_worker_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('ACTIVE', 'Aktiv'), ('COMPLETED', 'Tugallandi')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorderstage',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL),
        ),
    ]
