# Generated by Django 6.0.3 on 2026-03-27 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0006_productionorderstage_current_operator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PLANNED', 'Rejalashtirilgan'), ('IN_PROGRESS', 'Jarayonda'), ('QC_PENDING', 'Sifat Nazorati'), ('REPAIR', 'Brak / Qayta ishlov'), ('DELAYED', 'Kechikayotgan'), ('COMPLETED', 'Tugallangan'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASSED', 'Tasdiqlandi'), ('FAILED', 'Rad etildi (Brak)'), ('PENDING', 'Kutilmoqda')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('waste_weight', models.FloatField(default=0, help_text='kg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production_v2.productionorder')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_v2.productionorderstage')),
            ],
        ),
    ]
