# Generated by Django 6.0.3 on 2026-03-28 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0007_alter_productionorder_status_qualitycheck'),
        ('warehouse_v2', '0009_batchreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bunker',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bunker',
            name='last_occupied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='density',
            field=models.FloatField(default=0, help_text='Target density for this recipe (kg/m3)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='warehouse_v2.material'),
        ),
        migrations.AlterField(
            model_name='productionorderstage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACTIVE', 'Aktiv'), ('DONE', 'Tugallangan'), ('PAUSED', 'To‘xtatilgan'), ('FAILED', 'Xatolik / To‘xtagan')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='StageActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('START', 'Boshlash'), ('FINISH', 'Yakunlash'), ('FAIL', 'Xatolik'), ('PAUSE', 'To‘xtatish'), ('RESUME', 'Davom ettirish')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='production_v2.productionorder')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='production_v2.productionorderstage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
