# Generated by Django 6.0.3 on 2026-04-17 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0009_alter_stageactionlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq (Hisoblanmoqda)'), ('CLOSED', 'Yopilgan (Final)')], default='OPEN', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_output_qty', models.FloatField(default=0, help_text='Total blocks or output units')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cnc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cost_confidence', models.CharField(choices=[('REAL', 'Haqiqiy (Kiritilgan)'), ('ESTIMATED', 'Taxminiy (Avto-Taqsimlangan)')], default='ESTIMATED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OverheadCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(help_text='Masalan: Ijara, Amortizatsiya, Soliq qismi', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_costs', to='production_v2.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(help_text='Ishlangan soat yoki norma')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, help_text='Soatbay yoki ishlab chiqarilgan m3/stk uchun stavka', max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_costs', to='production_v2.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAS', 'Gaz'), ('ELECTRICITY', 'Elektr')], max_length=20)),
                ('quantity', models.FloatField(help_text='m3 or kWh')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Tarif narxi', max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_auto_calculated', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_usages', to='production_v2.productionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='production_v2.productionbatch'),
        ),
        migrations.AddField(
            model_name='bunkerload',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bunker_loads', to='production_v2.productionbatch'),
        ),
        migrations.AddField(
            model_name='zames',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zames_list', to='production_v2.productionbatch'),
        ),
    ]
