# Generated by Django 6.0.3 on 2026-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0010_productionbatch_overheadcost_laborcost_energyusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamesitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='zamesitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
