# Generated by Django 6.0.3 on 2026-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0011_zamesitem_total_cost_zamesitem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockproduction',
            name='status',
            field=models.CharField(choices=[('DRYING', 'Quritilmoqda'), ('READY', 'Tayyor'), ('DEFECT', 'Brak'), ('RESERVED', 'Band qilingan'), ('SOLD', 'Sotilgan')], default='DRYING', max_length=50),
        ),
        migrations.AlterField(
            model_name='blockproduction',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total volume in m3', max_digits=18),
        ),
        migrations.AlterField(
            model_name='blockproduction',
            name='weight_per_block',
            field=models.DecimalField(decimal_places=3, default=0, help_text='kg', max_digits=18),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ochiq (Hisoblanmoqda)'), ('CLOSED', 'Yopilgan (Final)'), ('CANCELLED', 'Bekor qilingan')], default='OPEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total completion percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PLANNED', 'Rejalashtirilgan'), ('IN_PROGRESS', 'Jarayonda'), ('QC_PENDING', 'Sifat Nazorati'), ('REPAIR', 'Brak / Qayta ishlov'), ('DELAYED', 'Kechikayotgan'), ('COMPLETED', 'Tugallangan'), ('CANCELLED', 'Bekor qilingan'), ('FAILED', 'Xatolik / To‘xtagan')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='productionorderstage',
            name='stage_type',
            field=models.CharField(choices=[('ZAMES', 'Zames (Mixing)'), ('DRYING', 'Quritish'), ('BUNKER', 'Bunker (Resting)'), ('FORMOVKA', 'Formovka (Molding)'), ('BLOK', 'Blok (Cutting/Sizing)'), ('CNC', 'CNC (Cutting)'), ('DEKOR', 'Dekor (Finishing)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productionorderstage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACTIVE', 'Aktiv'), ('DONE', 'Tugallangan'), ('PAUSED', 'To‘xtatilgan'), ('FAILED', 'Xatolik / To‘xtagan')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='zames',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('DONE', 'Tugallandi'), ('CANCELLED', 'Bekor qilindi'), ('FAILED', 'Xatolik / To‘xtagan')], default='PENDING', max_length=50),
        ),
    ]
