# Generated by Django 6.0.3 on 2026-04-17 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueCostEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(help_text='ZAMES, BLOCK', max_length=50)),
                ('reference_id', models.CharField(help_text='Zames ID yoki BlockProduction ID', max_length=50)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Ishlab chiqarish, Logistika', max_length=150)),
                ('code', models.CharField(help_text='CC-001', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xarajat Markazi',
                'verbose_name_plural': 'Xarajat Markazlari',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: 2026 Aprel Logistika Byudjeti', max_length=200)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, help_text='Avto hisoblanadi', max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('ACTIVE', 'Faol'), ('CLOSED', 'Yopilgan')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Qaysi xarajat hisobi uchun (majburiy emas)', on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalperiod')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.costcenter')),
            ],
            options={
                'verbose_name': 'Byudjet',
                'verbose_name_plural': 'Byudjetlar',
                'unique_together': {('fiscal_period', 'account', 'cost_center')},
            },
        ),
    ]
