# Generated by Django 6.0.3 on 2026-03-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('SALES', 'Sotuvlar'), ('INVENTORY', 'Ombor'), ('PRODUCTION', 'Ishlab chiqarish'), ('WASTE', 'Chiqindilar')], max_length=20)),
                ('period', models.CharField(max_length=100)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('file_size', models.CharField(default='0 KB', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('ERROR', 'Xato')], default='READY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
