# Generated by Django 6.0.3 on 2026-04-17 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: QQS 12%', max_length=100)),
                ('code', models.CharField(help_text='Ichki kod: VAT_12, VAT_0, EXEMPT', max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Soliq foizi (masalan: 12.00)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soliq stavkasi',
                'verbose_name_plural': 'Soliq stavkalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Hisob kodi (masalan: 5010, 9010)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Hisob nomi', max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Aktivlar'), ('LIABILITY', 'Majburiyatlar'), ('EQUITY', 'Kapital va zaxiralar'), ('REVENUE', 'Daromadlar'), ('EXPENSE', 'Xarajatlar'), ('CONTRA', 'Kontrar hisob')], help_text='Hisob turi', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Hisob tavsifi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text="System hisobi — o'chirish mumkin emas")),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text="Hisob qoldig'i (cached, recalculated)", max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Ota hisob (sub-account uchun)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Hisob',
                'verbose_name_plural': 'Hisoblar rejasi',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: 2026 Aprel', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False, help_text="Yopilgan davr — o'zgartirish mumkin emas")),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisobot davri',
                'verbose_name_plural': 'Hisobot davrlari',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(editable=False, help_text='Avtomatik: JE-00001', max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Operatsiya tavsifi')),
                ('source_type', models.CharField(choices=[('MANUAL', "Qo'lda kiritilgan"), ('WAREHOUSE', 'Ombor operatsiyasi'), ('PRODUCTION', 'Ishlab chiqarish'), ('SALE', 'Sotuv'), ('FINANCE', 'Moliya operatsiyasi'), ('TRANSFER', "Ichki o'tkazma"), ('ADJUSTMENT', 'Tuzatish yozuvi')], default='MANUAL', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='Manba obyekt ID (masalan: Invoice #5)', max_length=100, null=True)),
                ('source_description', models.CharField(blank=True, help_text="Masalan: 'Faktura INV-0042 uchun provodka'", max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('POSTED', 'Tasdiqlangan'), ('VOID', 'Bekor qilingan')], default='DRAFT', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Tashqi hujjat raqami', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Umumiy summa (informational)', max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.fiscalperiod')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_entries', to=settings.AUTH_USER_MODEL)),
                ('tax_rate', models.ForeignKey(blank=True, help_text="Qo'llaniladigan soliq stavkasi", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxrate')),
            ],
            options={
                'verbose_name': 'Buxgalteriya yozuvi',
                'verbose_name_plural': 'Buxgalteriya yozuvlari',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit summasi', max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Kredit summasi', max_digits=18)),
                ('description', models.CharField(blank=True, help_text='Qator tavsifi', max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Provodka qatori',
                'verbose_name_plural': 'Provodka qatorlari',
            },
        ),
    ]
