# Generated by Django 6.0.3 on 2026-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
