# Generated by Django 6.0.3 on 2026-03-26 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_v2', '0002_invoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('BANK', 'Bank (Perezichleniya)'), ('CARD', 'Karta'), ('DEBT', 'Qarz (Nasiya)')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('CONFIRMED', 'Tasdiqlangan'), ('SHIPPED', "Jo'natilgan"), ('COMPLETED', 'Yakunlangan'), ('CANCELLED', 'Bekor qilingan')], default='NEW', max_length=20),
        ),
    ]
