# Generated by Django 6.0.3 on 2026-03-27 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_v2', '0004_customer_company_name_customer_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='interest_level',
            field=models.CharField(choices=[('HIGH', 'Yuqori'), ('MEDIUM', "O'rtacha"), ('LOW', 'Past')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_status',
            field=models.CharField(choices=[('LEAD', 'Yangi Lead'), ('NEGOTIATION', 'Muzokara'), ('WON', 'Yutilgan'), ('LOST', 'Yutqazilgan')], default='LEAD', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manager_limit_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='production_order_id',
            field=models.IntegerField(blank=True, help_text='ID of the related production order if MTO', null=True),
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('CALL', "Telefon qo'ng'irog'i"), ('MEETING', 'Uchrashuv'), ('TELEGRAM', 'Telegram / Messencer'), ('EMAIL', 'Email'), ('OTHER', 'Boshqa')], default='CALL', max_length=20)),
                ('notes', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='sales_v2.customer')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
