# Generated by Django 6.0.3 on 2026-03-27 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_v2', '0006_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='Yetkazib berish shartnomasi', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('ACTIVE', 'Aktiv'), ('EXPIRED', "Muddati o'tgan"), ('CANCELLED', 'Bekor qilingan')], default='DRAFT', max_length=20)),
                ('terms', models.TextField(blank=True, help_text='Shartnoma shartlari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='sales_v2.customer')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NEW_ORDER', 'Yangi buyurtma'), ('PAYMENT_RECEIVED', "To'lov qabul qilindi"), ('ORDER_SHIPPED', "Buyurtma jo'natildi"), ('DEBT_REMINDER', 'Qarz eslatmasi'), ('CONTRACT_EXPIRY', 'Shartnoma muddati tugayapti')], max_length=30)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_via', models.CharField(default='LOG', help_text='LOG or TELEGRAM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_v2.customer')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
