# Generated by Django 6.0.3 on 2026-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_v2', '0007_contract_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('CONFIRMED', 'Tasdiqlangan'), ('IN_PRODUCTION', 'Ishlab chiqarishda'), ('READY', 'Tayyor'), ('SHIPPED', "Jo'natilgan"), ('EN_ROUTE', "Yo'lda"), ('DELIVERED', 'Yetkazildi'), ('COMPLETED', 'Yakunlangan'), ('CANCELLED', 'Bekor qilingan')], default='NEW', max_length=20),
        ),
    ]
