# Generated by Django 6.0.3 on 2026-04-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0010_productionbatch_overheadcost_laborcost_energyusage_and_more'),
        ('sales_v2', '0009_saleitem_batch_number_saleitem_source_warehouse'),
        ('warehouse_v2', '0010_inventoryaudit_inventoryauditline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='avg_margin_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit cost at time of sale', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='True if using AVG cost instead of Batch FIFO'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='margin_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='production_v2.productionbatch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='raw_material_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='warehouse_v2.rawmaterialbatch'),
        ),
    ]
