# Generated by Django 6.0.3 on 2026-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_v2', '0010_invoice_avg_margin_percent_invoice_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avg_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_status',
            field=models.CharField(choices=[('HEALTHY', "Sog'lom (Healthy)"), ('OVERDUE', "Muddati o'tgan (Overdue)")], default='HEALTHY', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.CharField(choices=[('VIP', 'VIP (Gold)'), ('REGULAR', 'Oddiy (Regular)'), ('RISK', 'Xavfli (Risk / Bad Debt)')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
