# Generated by Django 6.0.3 on 2026-04-05 20:06

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('passport_info', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_per_trip', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_type', models.CharField(choices=[('PER_KM', 'Kilometr bo‘yicha (Per KM)'), ('PER_TRIP', 'Reys bo‘yicha (Fixed per Trip)')], default='PER_KM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('EXPIRED', 'Muddati o‘tgan'), ('CANCELLED', 'Bekor qilingan')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='transport.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('EN_ROUTE', 'Yo‘lda'), ('DELIVERED', 'Yetkazildi'), ('COMPLETED', 'Yakunlandi'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('related_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='logistics.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_given', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('norm', models.DecimalField(decimal_places=2, help_text='Litr per 100km or total norm', max_digits=10)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='transport.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'To‘lov kutilmoqda'), ('PAID', 'To‘landi')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transport.driver')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.db.models.functions.datetime.Now())),
                ('from_location', models.CharField(default='Asosiy Zavod', max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('CLIENT', 'Mijozga yetkazish (Client)'), ('PROJECT', 'Ichki loyiha (Project)'), ('TRANSFER', 'Omborlararo o‘tkazma (Transfer)')], default='CLIENT', max_length=10)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_given', models.DecimalField(decimal_places=2, default=0, help_text="Berilgan yoqilg'i (litr)", max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('CONFIRMED', 'Tasdiqlangan'), ('COMPLETED', 'Yakunlandi'), ('CANCELLED', 'Bekor qilingan')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_waybills', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='transport.driver')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='waybill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='transport.waybill'),
        ),
    ]
