# Generated by Django 6.0.3 on 2026-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type_productiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
